### ISSUE TITLE
Bug: Uncaught TypeError: emberData_Debug.runInDebug is not a functiona

### ISSUE THREAD

**Issue by jking6884** [ef4/stupendous-rentals#2]
After successfully installing and running ember serve, I ran into this in the browser console.

![pasted image at 2017_09_07 11_51 am](https://user-images.githubusercontent.com/4825257/30190905-63ac95d6-940b-11e7-8fc9-6b3accea6bf2.png)

**Comment by ef4** [comment]
I think I fixed this a few hours ago, please pull from master and rerun yarn install and see if it's fixed. 

Maybe delete the node_modules directory first to be sure you're getting the new deps.

**Comment by jking6884** [comment]
Cool.  It seems to be working now.
