### ISSUE TITLE
Some bulk operations failed

### ISSUE THREAD

**Issue by goo32** [ef4/stupendous-rentals#5]
Trying to get this demo running on Ubuntu 16.04. I followed the readme and I believe all pre-reqs are good but when running "ember s" I get the following error:

> Error: Some bulk operations failed: [
>   {
>     "reason": "mapper [params.initialModels.attributes.description.sections] of different type, current_type [text], mer
> ged_type [long]",
>     "examples": [
>       "data-sources/master/default"
>     ]
>   }
> ]
>     at BulkOps.flush (/home/esadmin/stupendous-rentals/node_modules/@cardstack/elasticsearch/bulk-ops.js:44:13)
> 

Not sure how to fix this.

**Comment by ef4** [comment]
I think this is fixed by https://github.com/cardstack/cardstack/commit/dabd7c787f41f8e2e830b18f47603588342a1af6
